function doAddition(a, b) {
    return new Promise((resolve, reject)=> {
        if(a < 0)
            reject("First value must be 0 or greater");
        else
            resolve(a + b);
    });
}

function delayedDouble(num) {
    return new Promise((resolve, reject)=>{
        setTimeout(resolve, 0, num * 2);
    });
}

Promise.all([delayedDouble(12), doAddition(5, 100)])
    .then(results => console.log("The result of Promise.all: " + results))
    .catch(err => console.error("Error with Promise.all: " + err));

Promise.reject("Promise.reject test").catch(reason => console.error(reason));
