try {
    throw "ass";
} catch(err) {
    console.error(`Error: ${err}`);
} finally {
    console.log("Oh well");
}
